# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 pod 'SVProgressHUD'
target 'WifiAutoConnectTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WifiAutoConnectTest

end
