# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookWebTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'SnapKit', '~> 4.2.0'
  # Pods for FacebookWebTest

end
